export interface CareerBuilderInput {
  fullName: string;
  targetJobTitle: string;
  targetCompany: string;
  yearsExperience: string;
  experience: string;
  skills: string;
  jobDescription: string;
}

const STOP_WORDS = new Set([
  'the', 'and', 'a', 'to', 'of', 'in', 'for', 'with', 'on', 'is', 'are', 'you', 'we', 'our',
  'your', 'will', 'have', 'this', 'that', 'as', 'an', 'be', 'or', 'at', 'from', 'by', 'us',
]);

function parseSkills(skills: string): string[] {
  return skills
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

function extractKeywords(jobDescription: string, max = 5): string[] {
  const words = jobDescription
    .toLowerCase()
    .replace(/[^a-zA-Z\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 3 && !STOP_WORDS.has(w));

  const freq = new Map<string, number>();
  for (const w of words) freq.set(w, (freq.get(w) ?? 0) + 1);

  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, max)
    .map(([w]) => w);
}

function truncate(text: string, max: number): string {
  const trimmed = text.trim();
  return trimmed.length > max ? `${trimmed.slice(0, max)}…` : trimmed;
}

export function buildCV(input: CareerBuilderInput): string {
  const skills = parseSkills(input.skills);
  const keywords = extractKeywords(input.jobDescription);
  const name = input.fullName || 'Your Name';
  const title = input.targetJobTitle || 'Target Role';

  return `# ${name}
${title}${input.targetCompany ? ` · Applying to ${input.targetCompany}` : ''}

## Professional Summary
${input.yearsExperience || 'Motivated'} professional with hands-on experience in ${
    skills.slice(0, 3).join(', ') || 'the relevant field'
  }, bringing ${
    keywords.length ? `strengths in ${keywords.slice(0, 3).join(', ')}` : 'a strong work ethic'
  } to the ${title} role${input.targetCompany ? ` at ${input.targetCompany}` : ''}.

## Skills
${skills.length ? skills.map((s) => `- ${s}`).join('\n') : '- Add your key skills'}

## Experience
${input.experience.trim() || 'Describe your work history here.'}

## Education
- Add your university, degree, and expected graduation date here

---
*Generated by the Germany Student Hub smart template engine — review and personalize before sending.*
`;
}

export function buildCoverLetter(input: CareerBuilderInput): string {
  const name = input.fullName || '[Ihr Name]';
  const title = input.targetJobTitle || '[Position]';
  const company = input.targetCompany || 'Ihr Unternehmen';
  const skills = parseSkills(input.skills);
  const experienceSnippet = input.experience.trim() ? truncate(input.experience, 160) : '';

  return `Sehr geehrte Damen und Herren,

mit großem Interesse bewerbe ich mich auf die Position als ${title} bei ${company}. ${
    experienceSnippet ? `Durch meine bisherige Erfahrung — ${experienceSnippet} — ` : ''
  }bringe ich relevante Kenntnisse in ${skills.slice(0, 3).join(', ') || 'diesem Bereich'} mit.

${
  input.jobDescription.trim()
    ? 'Die in Ihrer Stellenausschreibung genannten Anforderungen entsprechen genau meinem Profil, und ich bin überzeugt, dass ich einen wertvollen Beitrag zu Ihrem Team leisten kann.'
    : 'Ich bin überzeugt, dass ich einen wertvollen Beitrag zu Ihrem Team leisten kann.'
}

Über eine Einladung zu einem persönlichen Gespräch würde ich mich sehr freuen.

Mit freundlichen Grüßen,
${name}`;
}

export function buildPitch(input: CareerBuilderInput): string {
  const title = input.targetJobTitle || 'this role';
  const skills = parseSkills(input.skills);
  const experienceSnippet = input.experience.trim() ? truncate(input.experience, 100) : '';

  return `Hi — I'm ${input.fullName || '[Your Name]'}, a student based in Germany with experience in ${
    skills.slice(0, 2).join(' and ') || 'my field'
  }. I saw the ${title} opening${input.targetCompany ? ` at ${input.targetCompany}` : ''} and I'd love to bring my skills to your team.${
    experienceSnippet ? ` Recently, I've been focused on ${experienceSnippet}.` : ''
  } Would you be open to a quick chat this week?`;
}
